source "https://rubygems.org"

ruby "3.3.1"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "sidekiq", "~> 7.2"
gem "redis", "~> 5.2"

group :development, :test do
  gem "rspec-rails"
end
